### ISSUE TITLE
Some code does not run

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [Calysto/calysto_hy#1]
Sorry for this very general issue title. I just tried your kernel with some examples from the Hy language documentation and I thought it might be most useful, if I shared that notebook with you, where it prints the errors in red as an output to a code cell. I don't really know what the problem is with it or with what code it happens and with what code it doesn't.

So here is the repo for the test notebook: https://github.com/ZelphirKaltstahl/hy-kernels-test-notebook

**Comment by dsblank** [comment]
Thanks for the test notebook!

I'll have to track these down. I know one workaround:

* use `raw-input` instead of `input`

The others might be Hy issues....

**Comment by dsblank** [comment]
I adjusted some things in a copy of your notebook, but other things I didn't know how to fix: 

https://github.com/Calysto/calysto_hy/blob/master/notebooks/Hylang%20Test.ipynb
