### ISSUE TITLE
Cannot import name `_compile_table`

### ISSUE THREAD

**Issue by gwerbin** [Calysto/calysto_hy#12]
With Hy version 0.15.0 and Metakernel version 0.20.14:

```
$ python -m calysto_hy install --help
```

```
ImportError: cannot import name '_compile_table' from 'hy.compiler'
```

I went into `hy.compiler.py` file, and I don't see anything named `_compile_table`. Was this a recent breaking change to Hy?

edit: I see that `_compile_table` is present in Hy 0.14.x, so yes it looks like an API change

**Comment by gilch** [comment]
It might be `_special_form_compilers` now, but I'm not sure if that would be enough. We've altered the compiler quite a bit, and more changes are planned. @kodiologist was working on that part.

**Comment by Kodiologist** [comment]
Yeah, I removed it. This was an internal name, so don't be too surprised that it disappeared. Likewise `_special_form_compilers`, which is similar but distinct.

**Comment by gwerbin** [comment]
It looks like it's being used to get completions:

https://github.com/Calysto/calysto_hy/blob/03f44b1a7acbfb264fd4d5d694b1652e005457b5/calysto_hy/kernel.py#L110-L124

Is there a supported alternative?

**Comment by Kodiologist** [comment]
Perhaps `hy.extra.reserved` has what you need.

**Comment by gilch** [comment]
If it's just completions you need, @ekaschalk has them working pretty well in [Jedhy](https://github.com/ekaschalk/jedhy).

**Comment by gwerbin** [comment]
@dsblank seeing as the fallback completion relies on an undocumented internal API, do you think completions should just be disabled if Jedhy isn't installed?

**Comment by dsblank** [comment]
Sure, that makes sense. We can add jedhy to requirements.txt and setup.py as well.

**Comment by falematte** [comment]
I get the same error. How did you solved it?

**Comment by dsblank** [comment]
If someone knows how to use git, you can try the PR available that should fix this. Let me know if you are working on it, otherwise I will try to try it soon.

**Comment by dsblank** [comment]
New version committed. Please let me know if anything fails. Thanks all!
