### ISSUE TITLE
Cannot open Tutorial notebook in Jupyter

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [Calysto/calysto_hy#2]
I downloaded the Tutorial notebook from your repo, but I cannot open it in my Jupyter. A modal is shown with the following message:

> Unreadable Notebook: /home/xiaolong/development/Hy/Tutorial.ipynb NotJSONError('Notebook does not appear to be JSON: \'\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang="en...',)

**Comment by dsblank** [comment]
You probably need to use the "Raw" button to download it. It looks fine to me:

http://nbviewer.jupyter.org/github/Calysto/calysto_hy/blob/master/notebooks/Tutorial.ipynb

nbviewer (the above link) also has a "Download" button. You can try that.

**Comment by ZelphirKaltstahl** [comment]
You are right, ofc. Somehow I thought right click download would give me that :D Guess this can be closed.
