### ISSUE TITLE
Is it possible to start up kernel with pre loaded hy libraries?

### ISSUE THREAD

**Issue by markomanninen** [Calysto/calysto_hy#5]
Hi,

this is a question rather than bug issue.

I'd like to require and import different macros and libraries on every kernel start up. Is it possible to define custom hy / python libraries somewhre so that they will be automaticly loaded on every start up of the calysto hy kernel?

**Comment by dsblank** [comment]
I thought it would be the case that one could code in ~/.ipython/metakernel/magics/startup.py like this:

```python
def register_magics(kernel):
    kernel.do_execute("(setv x 42)")
```

but something doesn't quite work. Need to investigate...

**Comment by markomanninen** [comment]
I'd appreciate that!

**Comment by dsblank** [comment]
Ok, I think there is a fix coming in metakernel, and you'll probably want to update calysto_hy as well. Waiting on github testing to complete. Then I'll push out a new metakernel, and the above should then work. Thanks for the question!

**Comment by dsblank** [comment]
Fixes have been  applied, and metakernel 0.20.5 has been released, both on pypi and conda. Summary: you can now run startup code by using the magic infrastructure, as shown above.

**Comment by markomanninen** [comment]
There is probably something else I need to import to startup.py, because I get the next error when opening hy notebook:

`[MetaKernelApp] ERROR | Can't load 'C:\Users\marko.manninen\.ipython\metakernel\magics\startup.py': error: 'CalystoHy' object has no attribute 'parser'`

?

I used exactly the same code from your preivous post: https://github.com/Calysto/calysto_hy/issues/5#issuecomment-326797864

**Comment by dsblank** [comment]
Can you update calysto_hy and metakernel packages?

```
pip install git+https://github.com/Calysto/calysto_hy.git -U
pip install metakernel -U
pip show calysto_hy metakernel
```

**Comment by markomanninen** [comment]
It seems both packages got updated now with -U option:

Name: calysto-hy
Version: 0.0.3
Summary: A Hy kernel for Jupyter based on MetaKernel
Home-page: https://github.com/Calysto/calysto_hy
Author: Douglas Blank
Author-email: doug.blank@gmail.com
License: UNKNOWN
Location:
c:\users\marko.manninen\appdata\local\continuum\anaconda2\envs\root36\lib\site-packages
Requires: metakernel, hy
---
Name: metakernel
Version: 0.20.6
Summary: Metakernel for Jupyter
Home-page: https://github.com/Calysto/metakernel
Author: Steven Silvester
Author-email: steven.silvester@ieee.org
License: UNKNOWN
Location:
c:\users\marko.manninen\appdata\local\continuum\anaconda2\envs\root36\lib\site-packages
Requires: pexpect, ipykernel

I'm running Jupyter Notebook from Anaconda Navigator. Other Python 2.7
environment I'm using, seems to have updated packages too, and everything
works as expected. Thanks for your efforts and keep up good work!

-Marko
