### ISSUE TITLE
Tagged release + PyPI upload?

### ISSUE THREAD

**Issue by gwerbin** [Calysto/calysto_hy#7]
Any reason not to do this? I've been using the kernel and apart from lacking `%matplotlib inline` support (which means I sadly can't use it for plotting on Jupyterhub) it seems stable and functional.

I'm not personally familiar with the PyPI release process, but I'd be happy to take it on if you think it's ready.

**Comment by dsblank** [comment]
Sure, that would be possible.

**Comment by dsblank** [comment]
Done!
