### ISSUE TITLE
Integrate jedi and jedhy as autocompletion

### ISSUE THREAD

**Issue by schuster-rainer** [Calysto/calysto_hy#8]
There is a new completion module from the hy-mode for emacs written in hy. I

https://github.com/ekaschalk/jedhy

also Jedi could be used for completion, as it is also default now for the ipykernel.

https://jedi.readthedocs.io/en/latest/docs/features.html#recipes

**Comment by dsblank** [comment]
This should be fairly easy. PR's accepted! If you, or anyone, would like pointers, I'd be glad to provide.

**Comment by schuster-rainer** [comment]
Your code I found looks pretty straight forward: get_completions.  Is this also compatible to the new ipython api for completions? Don't know whether this affects the jupyter interface. And to be fairly honest I don't really grasp the jedhy library. Have to dig in first. Don't know wheter I find any time soon, but I'd be glad to work on it. maybe  I can contact @ekaschalk somehow and ask for some pointers to get this done. I really love jupyter I'd love to see hy get this awesome completion in jupyter.

Thanks for your offer to help out and give pointers.

**Comment by ekaschalk** [comment]
Completion with `jedhy` is pretty straightforward, just given a `prefix`, another word for a raw string, do:

```
(setv jedhy (Actions :locals (locals) :globals (globals)))  ; calling with locals/globals captures current namespace
(.complete jedhy some-raw-string)
```

The tests here https://github.com/ekaschalk/jedhy/blob/master/tests/test_models.hy have examples.

Two notes:
1. I use jedhy only in the new-shell2 `hy-mode` develop branch.
2. Have to fix a bug that that provides false candidates after the dot if given exactly `something-that-doesnt-exist.`.

**Comment by schuster-rainer** [comment]
Okay.. that's pretty easy. Thanks for the hinters @ekaschalk . Will integrate it into calysto_hy and send a pull request

**Comment by dsblank** [comment]
Done! Thanks!

**Comment by schuster-rainer** [comment]
I will create another pull request to clean up the install and make it easier as soon as @ekaschalk uploaded jedhy to pypi. If Eric is fine with it I could also upload to pypi.
